[package]
name = "blackmarlin"
version = "0.1.0"
authors = ["doruk <dsekercioglu2003@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3


[dependencies]
chess = "3.2.0"
text_io = "0.1.8"
jemallocator = "0.3.2"
arrayvec = "0.7.1"
rand = "0.8.4"

[features]
standard = ["best_hist", "advanced_move_gen", "all_move", "q_search_move_ord"]
experimental = ["standard", "promo_move_ord"]
all = ["all_hist", "advanced_move_gen", "q_search_move_ord", "all_move", "promo_move_ord"]

advanced_move_gen = [] # more advanced move generation
q_search_move_ord = [] # use move ordering in quiescence search
promo_move_ord = []

all_hist = ["hist", "c_hist", "c_move", "cmh_table"]
best_hist = ["hist", "c_hist", "c_move", "q_c_hist"]
hist = []                                            # history heuristic
c_hist = []                                          # capture history
q_c_hist = []                                        # capture history in quiescence search
c_move = []                                          # counter move
cmh_table = []                                       # counter move history table

all_move = ["pv", "killer", "threat"]
pv = []                               # use pv in move generation
killer = []                           # use killer moves in move generation
threat = []                           # use threat moves from null move search in move generation
